import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DashBoardNav from "./DashboardComponents/DashBoardNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" overscroll-none bg-gray-50 {inter.className} relative">
        <DashBoardNav />
        {children}
      </body>
    </html>
  );
}
