/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/cowry.glb -t -r public --draco 
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ThreeElements } from '@react-three/fiber';

type GLTFResult = GLTF & {
   nodes: {
      band: THREE.Mesh;
      beeds: THREE.Mesh;
      rope: THREE.Mesh;
   };
   materials: {
      ['MAT_Cowery Beads']: THREE.MeshStandardMaterial;
   };
};

export function Cowry(props: ThreeElements['group']) {
   const { nodes, materials } = useGLTF(
      '/models/cowry.glb'
   ) as unknown as GLTFResult;
   return (
      <group {...props} dispose={null}>
         <mesh
            geometry={nodes.band.geometry}
            material={materials['MAT_Cowery Beads']}
            scale={0.9}
         />
         <mesh
            geometry={nodes.beeds.geometry}
            material={materials['MAT_Cowery Beads']}
            scale={0.9}
         />
         <mesh
            geometry={nodes.rope.geometry}
            material={materials['MAT_Cowery Beads']}
            scale={0.9}
         />
      </group>
   );
}

useGLTF.preload('/models/cowry.glb');
