/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/mask.glb -t -r public --draco 
*/

import * as THREE from 'three';
import React, { Suspense } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { ThreeElements } from '@react-three/fiber';
import ModelFallback from '../ModelFallback';

type GLTFResult = GLTF & {
   nodes: {
      Hair: THREE.Mesh;
      Mask: THREE.Mesh;
      Wire: THREE.Mesh;
   };
   materials: {
      Hair: THREE.MeshStandardMaterial;
      ['Face - Wood']: THREE.MeshStandardMaterial;
      Wire: THREE.MeshStandardMaterial;
   };
};

export function Mask(props: ThreeElements['group']) {
   const { nodes, materials } = useGLTF('/models/mask.glb') as unknown as GLTFResult;
   return (
      <Suspense fallback={<ModelFallback />}>
      <group {...props} dispose={null}>
         <mesh
            geometry={nodes.Hair.geometry}
            material={materials.Hair}
            rotation={[1.463, -0.102, 0.754]}
         />
         <mesh
            geometry={nodes.Mask.geometry}
            material={materials['Face - Wood']}
            rotation={[1.463, -0.102, 0.754]}
         />
         <mesh
            geometry={nodes.Wire.geometry}
            material={materials.Wire}
            rotation={[1.463, -0.102, 0.754]}
         />
      </group>
      </Suspense>
   );
}

useGLTF.preload('/models/mask.glb');
