export const testData = [
  {
    eventName: "eventName 1",
    evenDscription: "evenDscription 1",
    eventTime: "eventTime 1",
    eventDate: "eventDate 1",
    walletOne: "walletOne 1",
    walletTwo: "walletTwo 1",
    split: "split 1",
    price: "price 1",
    category: "museum",
    country: "zambia",
    id: "1",
  },
  {
    eventName: "eventName 2",
    evenDscription: "evenDscription 2",
    eventTime: "eventTime 2",
    eventDate: "eventDate 2",
    walletOne: "walletOne 2",
    walletTwo: "walletTwo 2",
    split: "split 2",
    price: "price 2",
    category: "art gallery",
    country: "southAfrica",
    id: "2",
  },
  {
    eventName: "eventName 3",
    evenDscription: "evenDscription 3",
    eventTime: "eventTime 3",
    eventDate: "eventDate 3",
    walletOne: "walletOne 3",
    walletTwo: "walletTwo 3",
    split: "split 3",
    price: "price 3",
    category: "museum",
    country: "zambia",
    id: "3",
  },
  {
    eventName: "eventName 4",
    evenDscription: "evenDscription 4",
    eventTime: "eventTime 4",
    eventDate: "eventDate 4",
    walletOne: "walletOne 4",
    walletTwo: "walletTwo 4",
    split: "split 4",
    price: "price 4",
    category: "museum",
    country: "southAfrica",
    id: "4",
  },
  {
    eventName: "eventName 5",
    evenDscription: "evenDscription 5",
    eventTime: "eventTime 5",
    eventDate: "eventDate 5",
    walletOne: "walletOne 5",
    walletTwo: "walletTwo 5",
    split: "split 5",
    price: "price 5",
    category: "museum",
    country: "zambia",
    id: "5",
  },
  {
    eventName: "eventName 6",
    evenDscription: "evenDscription 6",
    eventTime: "eventTime 6",
    eventDate: "eventDate 6",
    walletOne: "walletOne 6",
    walletTwo: "walletTwo 6",
    split: "split 6",
    price: "price 6",
    category: "museum",
    country: "zambia",
    id: "6",
  },
  {
    eventName: "eventName 7",
    evenDscription: "evenDscription 7",
    eventTime: "eventTime 7",
    eventDate: "eventDate 7",
    walletOne: "walletOne 7",
    walletTwo: "walletTwo 7",
    split: "split 7",
    price: "price 7",
    category: "art gallery",
    country: "southAfrica",
    id: "7",
  },
  {
    eventName: "eventName 8",
    evenDscription: "evenDscription 8",
    eventTime: "eventTime 8",
    eventDate: "eventDate 8",
    walletOne: "walletOne 8",
    walletTwo: "walletTwo 8",
    split: "split 8",
    price: "price 8",
    category: "museum",
    country: "zambia",
    id: "8",
  },
  {
    eventName: "eventName 9",
    evenDscription: "evenDscription 9",
    eventTime: "eventTime 9",
    eventDate: "eventDate 9",
    walletOne: "walletOne 9",
    walletTwo: "walletTwo 9",
    split: "split 9",
    price: "price 9",
    category: "art gallery",
    country: "southAfrica",
    id: "9",
  },
  {
    eventName: "eventName 10",
    evenDscription: "evenDscription 10",
    eventTime: "eventTime 10",
    eventDate: "eventDate 10",
    walletOne: "walletOne 10",
    walletTwo: "walletTwo 10",
    split: "split 10",
    price: "price 10",
    category: "museum",
    country: "southAfrica",
    id: "10",
  },
  {
    eventName: "eventName 11",
    evenDscription: "evenDscription 11",
    eventTime: "eventTime 11",
    eventDate: "eventDate 11",
    walletOne: "walletOne 11",
    walletTwo: "walletTwo 11",
    split: "split 11",
    price: "price 11",
    category: "art gallery",
    country: "zambia",
    id: "11",
  },
  {
    eventName: "eventName 12",
    evenDscription: "evenDscription 12",
    eventTime: "eventTime 12",
    eventDate: "eventDate 12",
    walletOne: "walletOne 12",
    walletTwo: "walletTwo 12",
    split: "split 12",
    price: "price 12",
    category: "museum",
    country: "southAfrica",
    id: "12",
  },
  {
    eventName: "eventName 13",
    evenDscription: "evenDscription 13",
    eventTime: "eventTime 13",
    eventDate: "eventDate 13",
    walletOne: "walletOne 13",
    walletTwo: "walletTwo 13",
    split: "split 13",
    price: "price 13",
    category: "museum",
    country: "zambia",
    id: "13",
  },
  {
    eventName: "eventName 14",
    evenDscription: "evenDscription 14",
    eventTime: "eventTime 14",
    eventDate: "eventDate 14",
    walletOne: "walletOne 14",
    walletTwo: "walletTwo 14",
    split: "split 14",
    price: "price 14",
    category: "museum",
    country: "zambia",
    id: "14",
  },
];
