/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DonationsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "donate"
      | "getWalletAddresses"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateWalletAddresses"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonationReceived"
      | "OwnershipTransferred"
      | "WalletAddressesUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish, AddressLike, boolean, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWalletAddresses",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWalletAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWalletAddresses",
    data: BytesLike
  ): Result;
}

export namespace DonationReceivedEvent {
  export type InputTuple = [
    donor: AddressLike,
    amount: BigNumberish,
    tokenAddress: AddressLike,
    recipientType: string,
    donorName: string,
    isAnonymous: boolean
  ];
  export type OutputTuple = [
    donor: string,
    amount: bigint,
    tokenAddress: string,
    recipientType: string,
    donorName: string,
    isAnonymous: boolean
  ];
  export interface OutputObject {
    donor: string;
    amount: bigint;
    tokenAddress: string;
    recipientType: string;
    donorName: string;
    isAnonymous: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WalletAddressesUpdatedEvent {
  export type InputTuple = [
    newProjectWallet: AddressLike,
    newCommunityWallet: AddressLike
  ];
  export type OutputTuple = [
    newProjectWallet: string,
    newCommunityWallet: string
  ];
  export interface OutputObject {
    newProjectWallet: string;
    newCommunityWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Donations extends BaseContract {
  connect(runner?: ContractRunner | null): Donations;
  waitForDeployment(): Promise<this>;

  interface: DonationsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  donate: TypedContractMethod<
    [
      amount: BigNumberish,
      tokenAddress: AddressLike,
      toProject: boolean,
      donorName: string,
      isAnonymous: boolean
    ],
    [void],
    "nonpayable"
  >;

  getWalletAddresses: TypedContractMethod<[], [[string, string]], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWalletAddresses: TypedContractMethod<
    [newProjectWallet: AddressLike, newCommunityWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      tokenAddress: AddressLike,
      toProject: boolean,
      donorName: string,
      isAnonymous: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getWalletAddresses"
  ): TypedContractMethod<[], [[string, string]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWalletAddresses"
  ): TypedContractMethod<
    [newProjectWallet: AddressLike, newCommunityWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DonationReceived"
  ): TypedContractEvent<
    DonationReceivedEvent.InputTuple,
    DonationReceivedEvent.OutputTuple,
    DonationReceivedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WalletAddressesUpdated"
  ): TypedContractEvent<
    WalletAddressesUpdatedEvent.InputTuple,
    WalletAddressesUpdatedEvent.OutputTuple,
    WalletAddressesUpdatedEvent.OutputObject
  >;

  filters: {
    "DonationReceived(address,uint256,address,string,string,bool)": TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;
    DonationReceived: TypedContractEvent<
      DonationReceivedEvent.InputTuple,
      DonationReceivedEvent.OutputTuple,
      DonationReceivedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WalletAddressesUpdated(address,address)": TypedContractEvent<
      WalletAddressesUpdatedEvent.InputTuple,
      WalletAddressesUpdatedEvent.OutputTuple,
      WalletAddressesUpdatedEvent.OutputObject
    >;
    WalletAddressesUpdated: TypedContractEvent<
      WalletAddressesUpdatedEvent.InputTuple,
      WalletAddressesUpdatedEvent.OutputTuple,
      WalletAddressesUpdatedEvent.OutputObject
    >;
  };
}
