import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DashBoardNav from "./DashboardComponents/DashBoardNav";
import DashboardNavBar from "./DashboardComponents/DashBoardNav";
import DashboardAdminInfo from "./DashboardComponents/DashboardAdminInfo";
import NavBar from "./DashboardComponents/components-new/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" overscroll-none bg-slate-100 {inter.className} relative">

           <NavBar />
        {children}
      </body>
    </html>
  );
}
