import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { NavBar } from "../components/navigation/navBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className } flex flex-col items-center bg-gray-50 dark:bg-slate-800`}>
        <NavBar/>
      {children}
      </body>
    </html>
  );
}
