'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { NavBar } from "../components/navigation/navBar";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
      <SessionProvider>
 
      {children}
      </SessionProvider>
      </body>
    </html>
  );
}
